# Generated by Django 3.0.6 on 2020-06-02 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiovan_app', '0002_auto_20200601_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorista',
            name='endereco',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tiovan_app.Endereco'),
        ),
    ]
