# Generated by Django 3.0.6 on 2020-06-04 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiovan_app', '0003_auto_20200601_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endereco',
            old_name='nome',
            new_name='nome_endereco',
        ),
        migrations.RemoveField(
            model_name='motorista',
            name='email',
        ),
        migrations.RemoveField(
            model_name='motorista',
            name='senha',
        ),
    ]
