# Generated by Django 3.0.6 on 2020-06-15 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiovan_app', '0006_auto_20200615_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='logradouro',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='latitude',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='longitude',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
