# Generated by Django 3.0.6 on 2020-06-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiovan_app', '0008_auto_20200620_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='logradouro',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
