# Generated by Django 3.0.6 on 2020-06-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiovan_app', '0009_auto_20200620_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorista',
            name='imagem',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
    ]
