# Generated by Django 3.0.6 on 2020-06-25 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiovan_app', '0010_auto_20200620_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instituicoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=20)),
                ('endereco', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tiovan_app.Endereco')),
            ],
        ),
    ]
