# Generated by Django 3.0.6 on 2020-06-25 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiovan_app', '0011_instituicoes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instituicoes',
            options={'verbose_name_plural': 'Instituicoes'},
        ),
    ]
