# Generated by Django 3.0.6 on 2020-06-27 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiovan_app', '0013_auto_20200627_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicoes',
            name='motorista',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tiovan_app.Motorista'),
        ),
    ]
