# Generated by Django 3.0.6 on 2020-06-29 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiovan_app', '0014_auto_20200627_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorista',
            name='celular',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='instituicoes',
            name='telefone',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('celular', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('cpf', models.CharField(max_length=15, unique=True)),
                ('endereco', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='tiovan_app.Endereco')),
                ('motorista', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='tiovan_app.Motorista')),
            ],
        ),
        migrations.CreateModel(
            name='Dependente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('endereco', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='tiovan_app.Endereco')),
                ('instituicao', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='tiovan_app.Instituicoes')),
                ('responsavel', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='tiovan_app.Responsavel')),
            ],
        ),
    ]
