# Generated by Django 3.0.6 on 2020-06-29 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiovan_app', '0015_auto_20200629_0111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependente',
            name='endereco',
        ),
    ]
